In [1]:
import pandas as pd
import numpy as np

In [7]:
# Y : continous data -> apply regression
data = pd.read_csv('Ecommerce Customers.csv')
data

Email  \
0        mstephenson@fernandez.com   
1                hduke@hotmail.com   
2                 pallen@yahoo.com   
3          riverarebecca@gmail.com   
4    mstephens@davidson-herman.com   
..                             ...   
495   lewisjessica@craig-evans.com   
496            katrina56@gmail.com   
497             dale88@hotmail.com   
498            cwilson@hotmail.com   
499      hannahwilson@davidson.com   

                                               Address            Avatar  \
0         835 Frank Tunnel\nWrightmouth, MI 82180-9605            Violet   
1       4547 Archer Common\nDiazchester, CA 06566-8576         DarkGreen   
2    24645 Valerie Unions Suite 582\nCobbborough, D...            Bisque   
3     1414 David Throughway\nPort Jason, OH 22070-1220       SaddleBrown   
4    14023 Rodriguez Passage\nPort Jacobville, PR 3...  MediumAquaMarine   
..                                                 ...               ...   
495  4483 Jones Motorway Suite 872\nLake Jamiefurt,...               Tan   
496  172 Owen Divide Suite 497\nWest Richard, CA 19320     PaleVioletRed   
497  0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...          Cornsilk   
498  680 Jennifer Lodge Apt. 808\nBrendachester, TX...              Teal   
499  49791 Rachel Heights Apt. 898\nEast Drewboroug...       DarkMagenta   

     Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0              34.497268    12.655651        39.577668              4.082621   
1              31.926272    11.109461        37.268959              2.664034   
2              33.000915    11.330278        37.110597              4.104543   
3              34.305557    13.717514        36.721283              3.120179   
4              33.330673    12.795189        37.536653              4.446308   
..                   ...          ...              ...                   ...   
495            33.237660    13.566160        36.417985              3.746573   
496            34.702529    11.695736        37.190268              3.576526   
497            32.646777    11.499409        38.332576              4.958264   
498            33.322501    12.391423        36.840086              2.336485   
499            33.715981    12.418808        35.771016              2.735160   

     Yearly Amount Spent  
0             587.951054  
1             392.204933  
2             487.547505  
3             581.852344  
4             599.406092  
..                   ...  
495           573.847438  
496           529.049004  
497           551.620145  
498           456.469510  
499           497.778642  

[500 rows x 8 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Email                 500 non-null    object 
 1   Address               500 non-null    object 
 2   Avatar                500 non-null    object 
 3   Avg. Session Length   500 non-null    float64
 4   Time on App           500 non-null    float64
 5   Time on Website       500 non-null    float64
 6   Length of Membership  500 non-null    float64
 7   Yearly Amount Spent   500 non-null    float64
dtypes: float64(5), object(3)
memory usage: 31.4+ KB


In [9]:
data.describe()

Avg. Session Length  Time on App  Time on Website  \
count           500.000000   500.000000       500.000000   
mean             33.053194    12.052488        37.060445   
std               0.992563     0.994216         1.010489   
min              29.532429     8.508152        33.913847   
25%              32.341822    11.388153        36.349257   
50%              33.082008    11.983231        37.069367   
75%              33.711985    12.753850        37.716432   
max              36.139662    15.126994        40.005182   

       Length of Membership  Yearly Amount Spent  
count            500.000000           500.000000  
mean               3.533462           499.314038  
std                0.999278            79.314782  
min                0.269901           256.670582  
25%                2.930450           445.038277  
50%                3.533975           498.887875  
75%                4.126502           549.313828  
max                6.922689           765.518462

In [10]:
# we can drop the first three columns
data_droped = data.copy()
data_droped.drop(columns=['Email', 'Address', 'Avatar'], inplace=True)

In [11]:
data_droped

Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0              34.497268    12.655651        39.577668              4.082621   
1              31.926272    11.109461        37.268959              2.664034   
2              33.000915    11.330278        37.110597              4.104543   
3              34.305557    13.717514        36.721283              3.120179   
4              33.330673    12.795189        37.536653              4.446308   
..                   ...          ...              ...                   ...   
495            33.237660    13.566160        36.417985              3.746573   
496            34.702529    11.695736        37.190268              3.576526   
497            32.646777    11.499409        38.332576              4.958264   
498            33.322501    12.391423        36.840086              2.336485   
499            33.715981    12.418808        35.771016              2.735160   

     Yearly Amount Spent  
0             587.951054  
1             392.204933  
2             487.547505  
3             581.852344  
4             599.406092  
..                   ...  
495           573.847438  
496           529.049004  
497           551.620145  
498           456.469510  
499           497.778642  

[500 rows x 5 columns]

In [12]:
data_droped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Avg. Session Length   500 non-null    float64
 1   Time on App           500 non-null    float64
 2   Time on Website       500 non-null    float64
 3   Length of Membership  500 non-null    float64
 4   Yearly Amount Spent   500 non-null    float64
dtypes: float64(5)
memory usage: 19.7 KB


In [16]:
data_droped['Avg. Session Length'].unique()

array([34.49726773, 31.92627203, 33.00091476, 34.30555663, 33.33067252,
       33.87103788, 32.0215955 , 32.73914294, 33.9877729 , 31.93654862,
       33.99257277, 33.87936082, 29.53242897, 33.19033404, 32.38797585,
       30.73772037, 32.1253869 , 32.33889932, 32.18781205, 32.61785606,
       32.91278511, 33.50308726, 31.53160448, 32.90325097, 34.507551  ,
       33.02933195, 33.54123131, 32.33598964, 33.11020506, 33.10543794,
       33.24190043, 33.4610563 , 32.17550124, 32.72836   , 32.82030995,
       33.61603789, 31.72165236, 32.86532717, 32.74936818, 32.56723048,
       32.07054622, 33.01954799, 33.79203908, 32.89398062, 32.04448613,
       34.55576799, 34.56455771, 32.7267846 , 33.11721873, 31.66104982,
       33.25633547, 33.90022441, 34.18777483, 33.76206924, 34.39016366,
       33.9252966 , 32.6882293 , 34.30187022, 32.84393022, 33.75499473,
       33.87978429, 33.07653561, 32.22729914, 32.78977262, 32.77260993,
       34.37425805, 33.07871721, 32.8052204 , 32.43075793, 32.17

In [17]:
data_droped['Time on App'].unique()

array([12.65565115, 11.10946073, 11.33027806, 13.71751367, 12.79518855,
       12.02692534, 11.36634831, 12.35195897, 13.38623528, 11.81412829,
       13.33897545, 11.584783  , 10.9612984 , 12.95922609, 13.14872569,
       12.63660605, 11.73386169, 12.01319469, 14.71538754, 13.98959256,
       11.36549203, 12.8779837 , 13.37856278, 11.65757592, 12.8936695 ,
       11.76581265, 12.78389178, 13.00781942, 11.98204499, 11.96502   ,
       12.30541781, 10.86916381, 13.38749211, 13.10450724, 11.63489325,
       11.9363865 , 11.7550237 , 11.98441752,  9.95497597, 12.48901322,
       11.73310622, 10.63456132, 12.50752537, 11.52987821, 13.41493474,
       12.17052542, 13.14655143, 12.98851015, 11.86412636, 11.39806419,
       13.85806246, 10.95679097, 10.32011626,  9.9845144 , 12.64519514,
       11.58865542, 13.76153285, 10.56829469, 11.83228622, 12.06415663,
       12.4955916 ,  9.60731469, 13.72862718, 11.67006592, 13.27631301,
       15.12699429, 12.69578975, 11.83547609, 11.30623234, 11.18

In [18]:
data_droped['Time on Website'].unique()

array([39.57766802, 37.26895887, 37.11059744, 36.72128268, 37.5366533 ,
       34.47687763, 36.68377615, 37.37335886, 37.53449734, 37.14516822,
       37.22580613, 37.08792607, 37.42021558, 36.1446667 , 36.61995708,
       36.21376309, 34.89409275, 38.38513659, 38.24411459, 37.1905038 ,
       37.60779252, 37.44102134, 38.73400629, 36.77260376, 37.63575588,
       37.73852495, 36.43064962, 37.85177917, 35.29308775, 37.27781174,
       36.16364817, 35.62244242, 35.69417499, 38.87804051, 35.36862633,
       38.768641  , 36.76572236, 37.0443614 , 37.38831487, 36.37147981,
       37.53429101, 37.49669015, 37.14286198, 36.88808605, 36.11243501,
       39.13109673, 37.33544589, 36.46200326, 36.58272777, 36.5944567 ,
       37.78026469, 37.26687826, 37.4534051 , 35.9334493 , 38.46832111,
       35.25224202, 39.25293095, 36.17312563, 36.81401056, 37.27122169,
       38.05260975, 36.49399255, 37.99702801, 37.40874848, 36.60077705,
       37.15762409, 35.35844431, 36.37506611, 37.68040323, 40.00

In [19]:
data_droped['Length of Membership'].unique()

array([4.08262063, 2.66403418, 4.1045432 , 3.12017878, 4.44630832,
       5.4935072 , 4.68501725, 4.43427343, 3.27343358, 3.20280607,
       2.48260777, 3.7132092 , 4.04642316, 3.91854184, 2.49454365,
       3.35784684, 3.13613272, 2.42080616, 1.51657558, 4.06454855,
       4.59993736, 1.55915194, 2.24514779, 3.91930231, 5.70515397,
       2.72173599, 4.64819932, 2.99636453, 3.92348875, 4.74257752,
       3.06236815, 3.47141345, 4.34306292, 2.82009723, 4.1245853 ,
       3.64928616, 1.84737042, 3.45238858, 4.65049127, 4.22243623,
       4.67127546, 4.64611998, 4.21449509, 4.64325855, 2.25868639,
       3.66310549, 3.87687518, 4.11322612, 3.2025312 , 3.19839927,
       5.97676813, 2.95266896, 2.09489171, 3.85547168, 2.87459691,
       3.39205049, 2.99576118, 3.31522475, 3.47191914, 3.97055563,
       4.63932033, 5.08121009, 4.80263063, 3.41468842, 3.46229885,
       5.37759358, 4.00178635, 3.43959056, 2.77952072, 3.55264977,
       2.60228711, 4.69432227, 3.40152234, 3.8515788 , 3.25811

In [20]:
data_droped['Yearly Amount Spent'].unique()

array([587.95105397, 392.20493344, 487.54750487, 581.85234404,
       599.40609205, 637.10244792, 521.57217476, 549.90414611,
       570.20040896, 427.1993849 , 492.60601272, 522.33740461,
       408.64035107, 573.41586733, 470.4527333 , 461.7807422 ,
       457.84769594, 407.70454755, 452.31567548, 605.0610388 ,
       534.70574381, 419.93877484, 436.51560573, 519.34098913,
       700.91709162, 423.17999168, 619.89563986, 486.83893477,
       529.53766534, 554.72208383, 497.5866713 , 447.68790654,
       588.71260551, 491.07322368, 507.44183234, 521.88357317,
       347.77692663, 490.73863214, 478.17033405, 537.84619527,
       532.75178758, 501.87443028, 591.19717818, 547.24434342,
       448.22982919, 549.86059046, 593.91500297, 563.67287336,
       479.73194909, 416.35835358, 725.58481406, 442.66725174,
       384.62657157, 451.45744687, 522.40414126, 483.67330802,
       520.89879445, 453.16950235, 496.65070807, 547.36514059,
       616.85152297, 507.212569  , 613.59932337, 483.15

In [21]:
data_droped.describe()

Avg. Session Length  Time on App  Time on Website  \
count           500.000000   500.000000       500.000000   
mean             33.053194    12.052488        37.060445   
std               0.992563     0.994216         1.010489   
min              29.532429     8.508152        33.913847   
25%              32.341822    11.388153        36.349257   
50%              33.082008    11.983231        37.069367   
75%              33.711985    12.753850        37.716432   
max              36.139662    15.126994        40.005182   

       Length of Membership  Yearly Amount Spent  
count            500.000000           500.000000  
mean               3.533462           499.314038  
std                0.999278            79.314782  
min                0.269901           256.670582  
25%                2.930450           445.038277  
50%                3.533975           498.887875  
75%                4.126502           549.313828  
max                6.922689           765.518462

# Data spliting

In [22]:
# determine x and y
X = data_droped.iloc[:,:-1]
Y = data_droped.iloc[:,-1]

In [23]:
X

Avg. Session Length  Time on App  Time on Website  Length of Membership
0              34.497268    12.655651        39.577668              4.082621
1              31.926272    11.109461        37.268959              2.664034
2              33.000915    11.330278        37.110597              4.104543
3              34.305557    13.717514        36.721283              3.120179
4              33.330673    12.795189        37.536653              4.446308
..                   ...          ...              ...                   ...
495            33.237660    13.566160        36.417985              3.746573
496            34.702529    11.695736        37.190268              3.576526
497            32.646777    11.499409        38.332576              4.958264
498            33.322501    12.391423        36.840086              2.336485
499            33.715981    12.418808        35.771016              2.735160

[500 rows x 4 columns]

In [24]:
Y

0      587.951054
1      392.204933
2      487.547505
3      581.852344
4      599.406092
          ...    
495    573.847438
496    529.049004
497    551.620145
498    456.469510
499    497.778642
Name: Yearly Amount Spent, Length: 500, dtype: float64

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=5)

# Apply scaling

In [26]:
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()
x_train_scaled = Scaler.fit_transform(x_train)
x_test_scaled = Scaler.transform(x_test)

# Model Building and Training

In [27]:
from sklearn.linear_model import LinearRegression
linear_regression_model = LinearRegression()
linear_regression_model.fit(x_train_scaled, y_train)

LinearRegression()

In [28]:
linear_regression_model.coef_

array([25.893244  , 39.18651905,  0.45583877, 60.44132741])

In [29]:
linear_regression_model.intercept_

498.3514243562842

In [31]:
y_predict = linear_regression_model.predict(x_test_scaled) 
y_predict

array([559.28329991, 478.50520821, 455.80631643, 538.42873404,
       480.61186059, 506.94174709, 499.47488213, 588.76713744,
       532.20847445, 519.15932732, 523.55702645, 435.6345149 ,
       499.86684312, 461.44268359, 589.75317842, 491.09265277,
       590.83923796, 685.45560631, 432.78197282, 439.97266672,
       389.10869285, 753.58048766, 505.98160795, 566.04431348,
       610.75349415, 421.44845291, 507.44736431, 599.97672337,
       438.26767699, 503.66110085, 451.78829806, 494.95898743,
       598.6323141 , 468.85107574, 423.0081068 , 464.06498575,
       590.92498952, 508.08649348, 467.29111452, 430.5102801 ,
       480.11392447, 417.27315723, 472.45106539, 514.0344006 ,
       464.43420273, 513.04273937, 531.06811235, 575.03731417,
       725.60637221, 411.64013915, 325.16736868, 685.40599957,
       554.52893049, 521.45644252, 431.22825716, 502.66086639,
       543.66728031, 488.44863431, 500.73370539, 584.43849549,
       557.78915843, 512.33803854, 535.30278156, 531.19

In [36]:
y_test.values

array([571.47103412, 478.58428601, 478.71935687, 536.13089686,
       497.38955776, 511.97985999, 492.5568337 , 585.9318443 ,
       532.75178758, 502.4097853 , 520.89879445, 442.72289157,
       469.38314617, 448.34042501, 591.43773557, 473.94985742,
       586.15587018, 684.16343102, 451.62861054, 441.89663152,
       387.53471631, 744.2218671 , 510.15981728, 560.44379217,
       595.8228367 , 421.32663126, 511.03878605, 604.33484007,
       449.07031944, 508.77190674, 443.19722103, 496.93344626,
       587.57479948, 468.44573723, 402.16712222, 476.76672415,
       584.21831349, 506.42385997, 444.05382657, 436.72055586,
       478.18305971, 421.96679419, 465.17662331, 513.15311185,
       465.88931271, 507.44183234, 529.04900413, 565.9943634 ,
       725.58481406, 398.16346853, 330.59444603, 689.78760417,
       560.56016062, 529.53766534, 445.06218551, 507.39006179,
       547.24434342, 495.29944255, 499.14015245, 573.30622226,
       556.29814117, 510.66179222, 543.13262629, 550.81

# Model Evaluation

In [48]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
MSE = mean_squared_error(y_test, y_predict)
MSE

95.78550863644479

In [49]:
MAE = mean_absolute_error(y_test, y_predict)
MAE

7.424561345028158

In [50]:
linear_regression_model.score(x_test_scaled, y_test)

0.9836351264700085

In [51]:
linear_regression_model.score(x_train_scaled, y_train)

0.9844358197636554

In [53]:
X.shape

(500, 4)

In [54]:
Y.shape

(500,)